# Autogenerated wrapper script for libosrmc_jll for aarch64-linux-gnu-cxx11
export libosrmc, osrmc_header

using CompilerSupportLibraries_jll
using OSRM_jll
using boost_jll
using Expat_jll
using Zlib_jll
using Bzip2_jll
JLLWrappers.@generate_wrapper_header("libosrmc")
JLLWrappers.@declare_library_product(libosrmc, "libosrmc.so.6")
JLLWrappers.@declare_file_product(osrmc_header)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OSRM_jll, boost_jll, Expat_jll, Zlib_jll, Bzip2_jll)
    JLLWrappers.@init_library_product(
        libosrmc,
        "lib/libosrmc.so",
        nothing,
    )

    JLLWrappers.@init_file_product(
        osrmc_header,
        "include/osrmc/osrmc.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
