# Autogenerated wrapper script for libosrmc_jll for x86_64-linux-gnu-cxx11
export libosrmc, osrmc_header

using OSRM_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libosrmc")
JLLWrappers.@declare_library_product(libosrmc, "libosrmc.so.6")
JLLWrappers.@declare_file_product(osrmc_header)
function __init__()
    JLLWrappers.@generate_init_header(OSRM_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libosrmc,
        "lib/libosrmc.so",
        nothing,
    )

    JLLWrappers.@init_file_product(
        osrmc_header,
        "include/osrmc/osrmc.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
